name: Feature Request
description: Suggest a new feature or improvement for PrisML
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: "I'm trying to predict user churn but need real-time streaming predictions for high-traffic apps..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like PrisML to solve this?
      placeholder: |
        ```typescript
        // Example API you'd like to see
        const stream = prisma.user.streamPredictions({
          model: churnModel,
          batchSize: 1000
        });
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you tried or considered?
      placeholder: "I tried batch predictions but it's too slow for my 100K+ user base..."

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How critical is this feature for your use case?
      options:
        - Blocker - Cannot use PrisML without this
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature is this?
      options:
        - Performance optimization
        - New algorithm support
        - Developer experience
        - Documentation
        - Platform compatibility
        - Integration (cloud/database)
        - Model lifecycle (training/deployment)
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your real-world scenario
      placeholder: "We're building a SaaS app that predicts lead quality. We need to score 10K leads per day..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can provide real-world data for benchmarking
